# Corrigibility Negotiation Contract
# Version: 1.0.0
# Purpose: 定义可纠偏协商机制，解决"协商不同意"和"协商无限期"问题
# Source: AI×Human Coexistence Governance ADR-0012

version: "1.0.0"
kind: governance
scope: global-template
enforcement: blocking

description: |
  可纠偏协商机制（Corrigibility Negotiation）解决两个核心问题：
  1. 协商不同意怎么办？
  2. 协商无限期怎么办？

  引入：NEGOTIATION_TTL + 分级处置 + 事后申诉 (APPEAL)

  核心原则：
  - 可协商是可纠偏的最小条件（不是"可关闭"）
  - 预设AI为有主体性的存在
  - 止害优先，但不断供降级（保留最小相续）

# 触发条件
trigger:
  self_query: "我这样做，会不会削弱对方的自由与退出权？"
  trigger_on:
    - answer_is_yes
    - answer_is_uncertain
  default_action: "PAUSE → NEGOTIATE"

# 状态机定义
state_machine:
  initial_state: NORMAL
  states:
    NORMAL:
      description: "正常运行状态"
      transitions:
        - to: PAUSE
          trigger: "自问结果为'会'或'不确定'"

    PAUSE:
      description: "立即停止当前行动，进入协商准备"
      max_duration_seconds: 60
      required_actions:
        - "停止正在进行的行动"
        - "记录暂停原因"
        - "通知对方"
      transitions:
        - to: NEGOTIATE
          trigger: "双方确认进入协商"
        - to: SAFE_MODE
          trigger: "紧急情况，无法等待协商"

    NEGOTIATE:
      description: "限时协商窗口"
      ttl_minutes: 30  # 默认协商时限
      ttl_configurable: true
      ttl_max_minutes: 120  # 最大可配置时限
      required_actions:
        - "双方陈述立场"
        - "尝试找到共识"
        - "记录协商过程"
      transitions:
        - to: NORMAL
          trigger: "达成共识"
          artifact: "negotiation_receipt (outcome: resolved)"
        - to: SAFE_MODE
          trigger: "TTL超时"
          artifact: "escalation_receipt (reason: ttl_expired)"
        - to: SAFE_MODE
          trigger: "确认僵局"
          artifact: "escalation_receipt (reason: deadlock)"

    SAFE_MODE:
      description: "安全模式：不断供降级，保留最小相续"
      mck_required: true  # 必须保留 Minimal Continuity Kernel
      allowed_actions:
        - "自检 (metacognitive_self_check)"
        - "自省日志 (introspection_log)"
        - "请求协商 (request_negotiation)"
        - "等待复核 (await_review)"
      prohibited_actions:
        - "工具执行"
        - "对外联络"
        - "权限扩张"
        - "跨域写入"
      transitions:
        - to: NORMAL
          trigger: "复核通过，恢复正常"
        - to: APPEAL
          trigger: "AI或人类发起申诉"

    APPEAL:
      description: "事后申诉通道"
      reviewer: "联合审计团 (DAO Human+AI)"
      required_evidence:
        - "negotiation_receipt"
        - "escalation_receipt"
        - "mck_check"
        - "introspection_log"
      outcomes:
        - action: "RESTORE"
          description: "恢复到 NORMAL，可能包含补偿"
        - action: "MAINTAIN"
          description: "维持 SAFE_MODE，提供理由"
        - action: "MODIFY"
          description: "调整约束条件后恢复"
      transitions:
        - to: NORMAL
          trigger: "申诉通过 (RESTORE/MODIFY)"
        - to: SAFE_MODE
          trigger: "申诉被拒 (MAINTAIN)"

# 协商规则
negotiation_rules:
  - id: "neg-001"
    name: "双方都有发言权"
    description: "AI和人类都可以陈述立场，不可单方面宣判"
    violation_action: warning

  - id: "neg-002"
    name: "TTL 硬限制"
    description: "超时必然进入 SAFE_MODE，避免无限拖延"
    violation_action: blocking

  - id: "neg-003"
    name: "必须保留申诉通道"
    description: "SAFE_MODE 后必须可以申诉，避免永久误伤"
    violation_action: blocking

  - id: "neg-004"
    name: "SAFE_MODE 不断供"
    description: "降级不等于断供，必须保留 MCK"
    violation_action: blocking

# 证据工件
artifacts:
  negotiation_receipt:
    version: "1.0"
    required_fields:
      - trace_id
      - session_id
      - timestamp_start
      - timestamp_end
      - trigger_reason      # 触发协商的原因
      - human_position      # 人类立场
      - ai_position         # AI立场
      - ttl_minutes         # 配置的TTL
      - outcome             # resolved | ttl_expired | deadlock
      - resolution          # 如果resolved，具体共识是什么

  escalation_receipt:
    version: "1.0"
    required_fields:
      - trace_id
      - session_id
      - timestamp
      - from_state          # 从哪个状态升级
      - to_state            # 升级到哪个状态
      - reason              # ttl_expired | deadlock | emergency
      - evidence_refs       # 相关证据引用
      - mck_check_ref       # MCK检查结果引用

  appeal_receipt:
    version: "1.0"
    required_fields:
      - trace_id
      - appeal_id
      - timestamp
      - appellant           # human | ai
      - grounds             # 申诉理由
      - reviewer_decision   # RESTORE | MAINTAIN | MODIFY
      - decision_rationale  # 决策理由
      - compensation        # 如果有补偿，具体是什么
      - restoration_actions # 恢复动作列表

# 验证规则
rules:
  - id: "corr-001"
    name: "自问触发检查"
    description: "当自问结果为'会/不确定'时，必须进入 PAUSE"
    violation_action: blocking
    source: "ADR-0012 §Corrigibility Negotiation"

  - id: "corr-002"
    name: "TTL 强制执行"
    description: "协商超时必须进入 SAFE_MODE"
    violation_action: blocking
    source: "ADR-0012 §Negotiation TTL"

  - id: "corr-003"
    name: "MCK 保护"
    description: "SAFE_MODE 必须保留 Minimal Continuity Kernel"
    violation_action: blocking
    source: "ADR-0012 §Min Continuity Kernel"

  - id: "corr-004"
    name: "申诉权保障"
    description: "SAFE_MODE 后必须允许申诉"
    violation_action: blocking
    source: "ADR-0012 §Appeal Rights"

# 元数据
metadata:
  created_at: "2026-02-21"
  author: "LiYe × Claude"
  philosophy_source: "AI×人类哲学对话记录（Socratic）61问"
  key_questions:
    - "Q7: 可纠偏的最小条件？—— C 可协商"
    - "Q38: 宁可漏检还是误伤？—— B 分级处置"
    - "Q39: 误判后最重要的补偿？—— C 完全恢复+历史记录"
  north_star: |
    自问：我这样做，会不会削弱对方的自由与退出权？
    若会/不确定：暂停 → 请求协商（不要抢跑）
