/**
 * Theme Factory Builder
 *
 * Purpose: Generate CSS variables and Tailwind config from contract IR
 *
 * This builder:
 * - ONLY reads contract via Adapter
 * - NEVER accesses knowledge/
 * - NEVER accesses _meta/contracts/
 * - NEVER accesses Skills/
 * - Does NOT make aesthetic decisions
 *
 * @version 1.0.0
 */

import { loadContract, SiteDesignIR } from '../adapters/site-design.adapter.ts';
import { writeFileSync, mkdirSync, existsSync } from 'fs';
import { join } from 'path';

// ============================================================================
// TYPE DEFINITIONS
// ============================================================================

interface BuildOutput {
  cssVars: string;
  tailwindConfig: string;
  htmlTemplate: string;
}

// ============================================================================
// GENERATORS
// ============================================================================

/**
 * Generate CSS custom properties from IR
 */
function generateCSSVars(ir: SiteDesignIR): string {
  const lines: string[] = [
    '/* Generated by theme-factory builder */',
    `/* Source: tracks/${ir.site.name}/site-design.contract.yaml */`,
    '/* DO NOT EDIT - Regenerate from contract */\n',
  ];

  // Root variables
  lines.push(':root {');

  // Colors
  lines.push('  /* Colors */');
  lines.push(`  --color-primary: ${ir.theme.colors.primary};`);
  lines.push(`  --color-background: ${ir.theme.colors.background};`);
  if (ir.theme.colors.secondary) {
    lines.push(`  --color-secondary: ${ir.theme.colors.secondary};`);
  }
  if (ir.theme.colors.surface) {
    lines.push(`  --color-surface: ${ir.theme.colors.surface};`);
  }
  if (ir.theme.colors.text?.primary) {
    lines.push(`  --color-text-primary: ${ir.theme.colors.text.primary};`);
  }
  if (ir.theme.colors.text?.secondary) {
    lines.push(`  --color-text-secondary: ${ir.theme.colors.text.secondary};`);
  }

  // Typography
  lines.push('\n  /* Typography */');
  lines.push(`  --font-primary: "${ir.theme.fonts.primary}", system-ui, sans-serif;`);
  lines.push(`  --font-heading: "${ir.theme.fonts.heading}", system-ui, sans-serif;`);
  if (ir.theme.fonts.mono) {
    lines.push(`  --font-mono: "${ir.theme.fonts.mono}", monospace;`);
  }

  // Layout
  lines.push('\n  /* Layout */');
  lines.push(`  --layout-max-width: ${ir.layout.maxWidth}px;`);
  if (ir.layout.contentMaxWidth) {
    lines.push(`  --layout-content-max-width: ${ir.layout.contentMaxWidth}px;`);
  }

  // Spacing
  lines.push('\n  /* Spacing */');
  lines.push(`  --spacing-base: ${ir.spacing.baseUnit}px;`);

  // Motion (constrained by contract)
  lines.push('\n  /* Motion */');
  lines.push(`  --motion-duration: ${ir.constraints.maxAnimationDuration}ms;`);

  lines.push('}');

  // Dark mode (if allowed)
  if (ir.theme.allowedModes.includes('dark')) {
    lines.push('\n/* Dark mode */');
    if (ir.theme.mode === 'dark') {
      lines.push('html {');
    } else {
      lines.push('html.dark {');
    }
    lines.push(`  color-scheme: dark;`);
    lines.push('}');
  }

  // Reduced motion (required by contract)
  if (ir.constraints.preferReducedMotion) {
    lines.push('\n/* Respect user preference */');
    lines.push('@media (prefers-reduced-motion: reduce) {');
    lines.push('  *, *::before, *::after {');
    lines.push('    animation-duration: 0.01ms !important;');
    lines.push('    transition-duration: 0.01ms !important;');
    lines.push('  }');
    lines.push('}');
  }

  return lines.join('\n');
}

/**
 * Generate Tailwind config from IR
 */
function generateTailwindConfig(ir: SiteDesignIR): string {
  const config = {
    theme: {
      extend: {
        colors: {
          primary: 'var(--color-primary)',
          background: 'var(--color-background)',
          ...(ir.theme.colors.secondary && { secondary: 'var(--color-secondary)' }),
          ...(ir.theme.colors.surface && { surface: 'var(--color-surface)' }),
        },
        fontFamily: {
          sans: ['var(--font-primary)'],
          heading: ['var(--font-heading)'],
          ...(ir.theme.fonts.mono && { mono: ['var(--font-mono)'] }),
        },
        maxWidth: {
          layout: 'var(--layout-max-width)',
          ...(ir.layout.contentMaxWidth && { content: 'var(--layout-content-max-width)' }),
        },
        spacing: Object.fromEntries(
          ir.spacing.scale.map((v, i) => [i, `${v}px`])
        ),
        borderRadius: Object.fromEntries(
          Object.entries(ir.borders.radius).map(([k, v]) => [k, `${v}px`])
        ),
        transitionDuration: {
          DEFAULT: 'var(--motion-duration)',
        },
      },
    },
    // Dark mode strategy based on contract
    darkMode: ir.theme.mode === 'dark' ? 'media' : 'class',
  };

  return [
    '// Generated by theme-factory builder',
    `// Source: tracks/${ir.site.name}/site-design.contract.yaml`,
    '// DO NOT EDIT - Regenerate from contract\n',
    'module.exports = ' + JSON.stringify(config, null, 2),
  ].join('\n');
}

/**
 * Generate minimal HTML template
 */
function generateHTMLTemplate(ir: SiteDesignIR): string {
  const darkClass = ir.theme.mode === 'dark' ? ' class="dark"' : '';

  return `<!DOCTYPE html>
<html lang="en"${darkClass}>
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title>${ir.site.name}</title>
  <link rel="stylesheet" href="./theme.css">
  <!-- Contract: ${ir.site.stack.join(', ')} -->
</head>
<body style="background: var(--color-background); color: var(--color-text-primary, inherit); font-family: var(--font-primary);">
  <main style="max-width: var(--layout-max-width); margin: 0 auto; padding: var(--spacing-base);">
    <h1 style="font-family: var(--font-heading); color: var(--color-primary);">${ir.site.name}</h1>
    <p>Theme generated from contract.</p>
  </main>
</body>
</html>
`;
}

// ============================================================================
// BUILD FUNCTION
// ============================================================================

/**
 * Build theme artifacts from contract
 *
 * @param trackId - Track identifier
 * @param outputDir - Output directory (default: tracks/<trackId>/dist)
 */
export function build(trackId: string, outputDir?: string): BuildOutput {
  // Load contract via Adapter (sole entry point)
  const ir = loadContract(trackId);

  // Generate artifacts
  const output: BuildOutput = {
    cssVars: generateCSSVars(ir),
    tailwindConfig: generateTailwindConfig(ir),
    htmlTemplate: generateHTMLTemplate(ir),
  };

  // Write to disk if outputDir specified
  if (outputDir) {
    if (!existsSync(outputDir)) {
      mkdirSync(outputDir, { recursive: true });
    }

    writeFileSync(join(outputDir, 'theme.css'), output.cssVars);
    writeFileSync(join(outputDir, 'tailwind.config.js'), output.tailwindConfig);
    writeFileSync(join(outputDir, 'index.html'), output.htmlTemplate);

    console.log(`✅ Theme built for ${trackId}`);
    console.log(`   Output: ${outputDir}`);
  }

  return output;
}

// ============================================================================
// CLI ENTRY POINT
// ============================================================================

/**
 * Usage:
 *   npx tsx builder.ts <site-id>                    # From themes repo (default)
 *   npx tsx builder.ts <site-id> --tracks           # From liye_os/tracks (legacy)
 *   npx tsx builder.ts <site-id> --output <dir>    # Custom output directory
 *
 * Environment:
 *   THEMES_REPO - Path to themes repository (default: ../../../themes)
 */
if (import.meta.url === `file://${process.argv[1]}`) {
  const args = process.argv.slice(2);
  const siteId = args.find(a => !a.startsWith('--'));
  const useTracksMode = args.includes('--tracks');
  const outputIndex = args.indexOf('--output');
  const customOutput = outputIndex !== -1 ? args[outputIndex + 1] : undefined;

  if (!siteId) {
    console.error('Usage: npx tsx builder.ts <site-id> [--tracks] [--output <dir>]');
    console.error('');
    console.error('Examples:');
    console.error('  npx tsx builder.ts kuachu                    # Build from themes repo');
    console.error('  npx tsx builder.ts example-track --tracks    # Build from liye_os/tracks');
    console.error('  npx tsx builder.ts kuachu --output ./dist    # Custom output');
    process.exit(1);
  }

  try {
    // Determine paths based on mode
    const themesRepo = process.env.THEMES_REPO || join(process.cwd(), '..', 'themes');
    const contractRoot = useTracksMode ? './tracks' : join(themesRepo, 'sites');
    const defaultOutput = useTracksMode
      ? `./tracks/${siteId}/dist`
      : join(themesRepo, 'sites', siteId);

    const outputDir = customOutput || defaultOutput;

    // Load contract from appropriate location
    const ir = loadContract(siteId, contractRoot);

    // Generate artifacts
    const output: BuildOutput = {
      cssVars: generateCSSVars(ir),
      tailwindConfig: generateTailwindConfig(ir),
      htmlTemplate: generateHTMLTemplate(ir),
    };

    // Write to disk
    if (!existsSync(outputDir)) {
      mkdirSync(outputDir, { recursive: true });
    }

    writeFileSync(join(outputDir, 'theme.css'), output.cssVars);
    writeFileSync(join(outputDir, 'tailwind.config.js'), output.tailwindConfig);
    writeFileSync(join(outputDir, 'index.html'), output.htmlTemplate);

    console.log(`✅ Theme built for ${siteId}`);
    console.log(`   Contract: ${contractRoot}/${siteId}/site-design.contract.yaml`);
    console.log(`   Output: ${outputDir}`);
  } catch (error) {
    console.error(error);
    process.exit(1);
  }
}
