/**
 * C1 tests — canonical_json.mjs token-preserving serializer.
 * Run: node --test .claude/scripts/learning/tests/*.test.mjs
 *
 * Asserts byte-equality with REAL Python json.dumps output (fixtures/divergence_vectors.json,
 * generated by golden_harness.py / python3 stdlib) across the SPEC §1.7.X divergence domain,
 * and proves that naive JSON.parse + JSON.stringify would diverge (the failure mode
 * token-preservation avoids).
 */
import { test } from 'node:test';
import assert from 'node:assert/strict';
import { readFileSync } from 'node:fs';
import { fileURLToPath } from 'node:url';
import { dirname, join } from 'node:path';

import {
  parseCanonical,
  emitCanonical,
  sha256Prefixed,
  hashCanonical,
  codePointCompare,
  makeObjectNode,
  makeStringNode,
  getEntry,
  astToValue,
  containsNativeNumber,
} from '../canonical_json.mjs';

const HERE = dirname(fileURLToPath(import.meta.url));
const fixture = JSON.parse(readFileSync(join(HERE, 'fixtures', 'divergence_vectors.json'), 'utf-8'));

test('§1.7.X divergence vectors: emitCanonical(parseCanonical) byte-equals Python json.dumps', () => {
  for (const v of fixture.vectors) {
    const round = emitCanonical(parseCanonical(v.python));
    assert.equal(round, v.python, `vector ${v.label}: round-trip must byte-equal Python output`);
  }
});

test('composite doc byte-equals Python (recursive key sort + compact + raw scalars)', () => {
  const round = emitCanonical(parseCanonical(fixture.composite_python));
  assert.equal(round, fixture.composite_python);
});

test('naive JSON.parse+JSON.stringify DIVERGES (numbers) where token-preservation does not', () => {
  // The genuine Python<->Node divergence is NUMBER formatting (int/float repr + big-int
  // precision). NOTE: U+2028/U+2029 are emitted RAW by BOTH Python (ensure_ascii=False)
  // AND Node JSON.stringify, so they do NOT diverge — token-preservation matters for numbers.
  const diverging = new Set([
    'float_1_0', 'float_1e16', 'float_1e-7', 'float_neg0', 'bigint_lossless',
  ]);
  for (const v of fixture.vectors) {
    if (!diverging.has(v.label)) continue;
    const naive = JSON.stringify(JSON.parse(v.python));
    assert.notEqual(naive, v.python, `vector ${v.label}: JSON.stringify SHOULD diverge from Python`);
    // …and our canonicalizer must NOT diverge:
    assert.equal(emitCanonical(parseCanonical(v.python)), v.python, `vector ${v.label}: emitCanonical must match Python`);
  }
});

test('U+2028/U+2029 round-trip RAW at runtime (both Python & Node emit them raw, NOT escaped)', () => {
  // Constructed at runtime so no raw separator byte is committed (repo no-bidi gate forbids it).
  for (const cp of [0x2028, 0x2029]) {
    const token = '"a' + String.fromCharCode(cp) + 'b"'; // a JSON string token holding a raw separator
    const round = emitCanonical(parseCanonical(token));
    assert.equal(round, token, 'separator must pass through byte-for-byte (token preservation)');
    assert.ok(!round.includes('\\u202'), 'must NOT be escaped (matches emit_fact ensure_ascii=False)');
  }
});

test('sha256Prefixed matches a known vector', () => {
  // sha256("a") = ca978112ca1bbdcafac231b39a23dc4da786eff8147c4e72b9807785afee48bb
  assert.equal(
    sha256Prefixed('a'),
    'sha256:ca978112ca1bbdcafac231b39a23dc4da786eff8147c4e72b9807785afee48bb',
  );
});

test('hashCanonical is deterministic and order-independent for object keys', () => {
  const a = makeObjectNode([['b', makeStringNode('2')], ['a', makeStringNode('1')]]);
  const b = makeObjectNode([['a', makeStringNode('1')], ['b', makeStringNode('2')]]);
  assert.equal(emitCanonical(a), '{"a":"1","b":"2"}');
  assert.equal(hashCanonical(a), hashCanonical(b));
});

test('object keys sort by code point (uppercase before lowercase, matches Python)', () => {
  const node = makeObjectNode([
    ['b', makeStringNode('x')],
    ['Z', makeStringNode('x')],
    ['a', makeStringNode('x')],
  ]);
  assert.equal(emitCanonical(node), '{"Z":"x","a":"x","b":"x"}');
  assert.ok(codePointCompare('Z', 'a') < 0);
});

test('getEntry / astToValue realize', () => {
  const node = parseCanonical('{"a":1,"b":"s","c":true,"d":null,"e":["x",2]}');
  assert.equal(emitCanonical(getEntry(node, 'b')), '"s"');
  assert.deepEqual(astToValue(node), { a: 1, b: 's', c: true, d: null, e: ['x', 2] });
});

test('containsNativeNumber detects native numbers (NUMERIC_NOT_STRING policy)', () => {
  assert.equal(containsNativeNumber(parseCanonical('{"acos":"0.42","cvr":"0.1"}')), false);
  assert.equal(containsNativeNumber(parseCanonical('{"acos":0.42}')), true);
  assert.equal(containsNativeNumber(parseCanonical('{"nested":{"x":["1",2]}}')), true);
  assert.equal(containsNativeNumber(parseCanonical('{"nested":{"x":["1","2"]}}')), false);
});

test('parser rejects malformed / trailing content', () => {
  assert.throws(() => parseCanonical('{bad}'));
  assert.throws(() => parseCanonical('{"a":1} trailing'));
  assert.throws(() => parseCanonical('"unterminated'));
  assert.throws(() => parseCanonical('[1,]'));
  assert.throws(() => parseCanonical('{"a":}'));
});
