/**
 * Evidence Writer
 *
 * Generates evidence_package.md and dry_run_plan.md files
 * into trace directories for audit and review.
 *
 * Week3: Only generates files, no real write operations.
 */

import { writeFileSync, readFileSync, existsSync, mkdirSync } from 'fs';
import { join, dirname } from 'path';

const TRACE_BASE_DIR = process.env.TRACE_BASE_DIR || '.liye/traces';

/**
 * Write Evidence Package to trace directory
 *
 * @param {Object} params
 * @param {string} params.trace_id - Trace identifier
 * @param {string} params.kind - 'evidence_package' | 'dry_run_plan'
 * @param {Object} params.data - Data to include in evidence
 * @param {string} params.data.decision - Governance decision
 * @param {string} params.data.origin - Data origin
 * @param {boolean} params.data.mock_used - Whether mock was used
 * @param {string} params.data.policy_version - Policy version
 * @param {string} params.data.task - Original user task/message
 * @param {string} params.data.tenant_id - Tenant identifier
 * @param {string} params.data.channel - Source channel (e.g., 'feishu')
 * @param {Array} params.data.why - Why points
 * @param {string} params.baseDir - Base directory for traces (optional)
 * @returns {Object} { success, filePath, error }
 */
export function writeEvidencePackage({ trace_id, kind, data, baseDir }) {
  const traceBaseDir = baseDir || TRACE_BASE_DIR;
  const traceDir = join(traceBaseDir, trace_id);
  const fileName = kind === 'dry_run_plan' ? 'dry_run_plan.md' : 'evidence_package.md';
  const filePath = join(traceDir, fileName);

  try {
    // Ensure trace directory exists
    if (!existsSync(traceDir)) {
      mkdirSync(traceDir, { recursive: true });
    }

    // Load existing verdict if available
    let verdict = null;
    const verdictPath = join(traceDir, 'verdict.json');
    if (existsSync(verdictPath)) {
      try {
        verdict = JSON.parse(readFileSync(verdictPath, 'utf-8'));
      } catch (e) {
        console.warn('[EvidenceWriter] Could not load verdict.json:', e.message);
      }
    }

    // Generate content based on kind
    const content = kind === 'dry_run_plan'
      ? generateDryRunPlan(trace_id, data, verdict)
      : generateEvidencePackage(trace_id, data, verdict);

    writeFileSync(filePath, content, 'utf-8');

    console.log(`[EvidenceWriter] Generated ${fileName} at ${filePath}`);
    return { success: true, filePath, fileName };

  } catch (e) {
    console.error('[EvidenceWriter] Failed to write:', e.message);
    return { success: false, error: e.message };
  }
}

/**
 * Generate Evidence Package markdown content
 */
function generateEvidencePackage(traceId, data, verdict) {
  const now = new Date().toISOString();
  const decision = data.decision || verdict?.decision || 'UNKNOWN';
  const origin = data.origin || 'unknown';
  const mockUsed = data.mock_used ?? false;
  const policyVersion = data.policy_version || 'unknown';
  const task = data.task || '(no task provided)';
  const tenantId = data.tenant_id || 'default';
  const channel = data.channel || 'unknown';

  // Generate Why section
  const whyPoints = data.why || getDefaultWhyPoints(decision);
  const whySection = whyPoints.map(p => `- ${p}`).join('\n');

  // Proposed next steps based on decision
  const nextSteps = getNextSteps(decision);

  return `# Evidence Package

**Generated**: ${now}

---

## Trace Information

| Field | Value |
|-------|-------|
| **Trace ID** | \`${traceId}\` |
| **Decision** | **${decision}** |
| **Origin** | \`${origin}\` |
| **Mock Used** | \`${mockUsed}\` |
| **Policy Version** | \`${policyVersion}\` |

---

## Why

${whySection}

---

## Inputs

| Field | Value |
|-------|-------|
| **Task** | ${task} |
| **Tenant ID** | \`${tenantId}\` |
| **Channel** | \`${channel}\` |

---

## Proposed Next Steps

${nextSteps.map(s => `- ${s}`).join('\n')}

> **Note**: This evidence package is for review only. No write operations have been executed.

---

## Links

- **Trace Directory**: \`.liye/traces/${traceId}/\`
- **Events Log**: \`.liye/traces/${traceId}/events.ndjson\`
- **Verdict**: \`.liye/traces/${traceId}/verdict.json\`

---

*Generated by LiYe OS Evidence Writer (Week3)*
`;
}

/**
 * Generate Dry Run Plan markdown content
 */
function generateDryRunPlan(traceId, data, verdict) {
  const now = new Date().toISOString();
  const decision = data.decision || verdict?.decision || 'UNKNOWN';
  const origin = data.origin || 'unknown';
  const mockUsed = data.mock_used ?? false;
  const task = data.task || '(no task provided)';

  // Simulated actions based on task
  const simulatedActions = generateSimulatedActions(task, decision);

  return `# Dry Run Plan

**Generated**: ${now}

---

## Overview

This is a **simulation plan** for the requested task. No real API calls or write operations will be made.

| Field | Value |
|-------|-------|
| **Trace ID** | \`${traceId}\` |
| **Decision** | **${decision}** |
| **Origin** | \`${origin}\` |
| **Mock Used** | \`${mockUsed}\` |

---

## Original Request

> ${task}

---

## Simulated Actions

${simulatedActions.map((a, i) => `### Step ${i + 1}: ${a.name}

- **Type**: ${a.type}
- **Target**: ${a.target}
- **Expected Outcome**: ${a.outcome}
- **Risk Level**: ${a.risk}
`).join('\n')}

---

## Safety Guarantees

- ✅ **No Real Writes**: All actions are simulated
- ✅ **Write Blocker Active**: Any write attempt would be blocked
- ✅ **Audit Trail**: All actions logged to trace

---

## Next Steps

1. Review this plan with stakeholders
2. If approved, generate Evidence Package for formal review
3. Only after full approval, consider real execution (requires separate authorization)

---

*Generated by LiYe OS Dry Run Planner (Week3)*
`;
}

/**
 * Get default Why points based on decision
 */
function getDefaultWhyPoints(decision) {
  const points = {
    ALLOW: [
      '通过治理检查（read-only 操作）',
      '符合 Phase 1 策略约束',
      '可生成 dry-run 计划用于复核'
    ],
    BLOCK: [
      '风险或不确定性过高',
      '不符合当前策略约束',
      '需要补充信息或调整请求'
    ],
    DEGRADE: [
      'AGE 服务不可达',
      '已降级到 mock fallback',
      '结果可用但受限，建议稍后重试'
    ],
    UNKNOWN: [
      '无法确定决策状态',
      '请检查系统配置',
      '建议联系管理员'
    ]
  };
  return points[decision] || points.UNKNOWN;
}

/**
 * Get next steps based on decision
 */
function getNextSteps(decision) {
  const steps = {
    ALLOW: [
      '查看 dry-run 计划确认执行路径',
      '如需执行，提交审批流程',
      '保留此 evidence 作为审计记录'
    ],
    BLOCK: [
      '查看阻止原因，调整请求参数',
      '咨询管理员获取更多权限',
      '重新提交修改后的请求'
    ],
    DEGRADE: [
      '稍后重试以获取真实数据',
      '当前 mock 数据仅供参考',
      '联系运维检查 AGE 服务状态'
    ],
    UNKNOWN: [
      '检查系统日志获取更多信息',
      '联系技术支持',
      '重新提交请求'
    ]
  };
  return steps[decision] || steps.UNKNOWN;
}

/**
 * Generate simulated actions for dry run plan
 */
function generateSimulatedActions(task, decision) {
  // Default simulated actions (simplified for Week3)
  return [
    {
      name: '查询广告数据',
      type: 'READ',
      target: 'Amazon Ads API - Campaign Metrics',
      outcome: '获取 ACOS、花费、销售额等指标',
      risk: 'LOW (只读操作)'
    },
    {
      name: '分析浪费支出',
      type: 'ANALYZE',
      target: 'Wasted Spend Strategy',
      outcome: '识别高点击零转化的搜索词',
      risk: 'LOW (本地计算)'
    },
    {
      name: '生成优化建议',
      type: 'RECOMMEND',
      target: 'Strategy Engine',
      outcome: '生成否定关键词建议列表',
      risk: 'LOW (仅建议，不执行)'
    }
  ];
}

/**
 * Check if evidence file exists for a trace
 */
export function evidenceExists(traceId, kind = 'evidence_package', baseDir) {
  const traceBaseDir = baseDir || TRACE_BASE_DIR;
  const fileName = kind === 'dry_run_plan' ? 'dry_run_plan.md' : 'evidence_package.md';
  const filePath = join(traceBaseDir, traceId, fileName);
  return existsSync(filePath);
}

/**
 * Get evidence file path
 */
export function getEvidencePath(traceId, kind = 'evidence_package', baseDir) {
  const traceBaseDir = baseDir || TRACE_BASE_DIR;
  const fileName = kind === 'dry_run_plan' ? 'dry_run_plan.md' : 'evidence_package.md';
  return join(traceBaseDir, traceId, fileName);
}

export default { writeEvidencePackage, evidenceExists, getEvidencePath };
