ess_version: "0.1"

metadata:
  skill_id: "liye-os:sfc-lint"
  name: "SFC Lint"
  visibility: "private"
  version: "0.1.0"

trigger:
  commands: ["/sfc-lint"]
  patterns: ["sfc lint", "lint skill", "validate skill frontmatter"]

input:
  schema:
    type: object
    required: ["skill_dir"]
    properties:
      skill_dir:
        type: string
        description: "Skill directory to lint"

execution:
  type: "script"
  runtime: "node"
  entry: ".claude/scripts/sfc_lint.mjs"
  args:
    - "{{skill_dir}}"

output:
  contract:
    report_dir: "docs/reports/ess/sfc-lint"
    report_name: "ESS-SFC-LINT-{{timestamp}}.md"
    trace_path: "traces/ESS-TRACE-{{timestamp}}.yaml"

governance:
  trace_enabled: true
  constitution: "_meta/governance/SKILL_CONSTITUTION_v0.1.md"
  policy: "_meta/policies/DEFAULT_SKILL_POLICY.md"
